# Generated by Django 4.1.1 on 2022-10-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_alter_productcategorymodel_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSizeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("symbol", models.CharField(max_length=16)),
            ],
        ),
        migrations.AlterField(
            model_name="productcategorymodel",
            name="image",
            field=models.ImageField(
                default="default/category.jpg", upload_to="product/category/image/"
            ),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="image",
            field=models.ImageField(
                default="default/product.jpg", upload_to="product/image/"
            ),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="size",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productsizemodel",
            ),
        ),
    ]
