# Generated by Django 4.1.1 on 2022-10-06 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_productbrandmodel"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductBrandModel",
        ),
    ]
