# Generated by Django 4.1.1 on 2022-10-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_delete_productbrandmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductBrandModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("description", models.TextField(max_length=500)),
            ],
        ),
    ]
