# Generated by Django 4.1.1 on 2022-10-06 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_productbrandmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="product.productbrandmodel",
            ),
        ),
    ]
